name: Build changelog and create a release
description: Generate changelogs and create a release using https://github.com/marketplace/actions/release-changelog-builder
runs:
  using: 'composite'
  steps:
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Create Release
      uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
      with:
        body: ${{steps.build_changelog.outputs.changelog}}