name: Generate changelogs
description: Generate changelogs using https://github.com/requarks/changelog-action
runs:
  using: 'composite'
  steps:
    - name: Find latest tag
      run: |
        echo "LATEST_TAG=$(git tag -l | sed -n 2p)" >> $GITHUB_ENV
        echo Found tag: $(git tag -l | sed -n 2p)
      shell: bash
    - name: Echo latest tag from env
      run: |
        echo Env tag: ${{ env.LATEST_TAG }}
      shell: bash
    - name: Changelog action
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: v0.0.2
