name: Pull request
on: pull_request
jobs:
  changelog_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/changelog_ci
        with:
          release_version: v0.0.1