name: 'Push'
on:
  push:
    tags:
      - '*'
jobs:
  changelog_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/changelog_release